/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyMapRouteImport } from './routes/study-map'
import { Route as DistrictQuizRouteImport } from './routes/district-quiz'
import { Route as IndexRouteImport } from './routes/index'

const StudyMapRoute = StudyMapRouteImport.update({
  id: '/study-map',
  path: '/study-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictQuizRoute = DistrictQuizRouteImport.update({
  id: '/district-quiz',
  path: '/district-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/district-quiz': typeof DistrictQuizRoute
  '/study-map': typeof StudyMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/district-quiz': typeof DistrictQuizRoute
  '/study-map': typeof StudyMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/district-quiz': typeof DistrictQuizRoute
  '/study-map': typeof StudyMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/district-quiz' | '/study-map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/district-quiz' | '/study-map'
  id: '__root__' | '/' | '/district-quiz' | '/study-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictQuizRoute: typeof DistrictQuizRoute
  StudyMapRoute: typeof StudyMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-map': {
      id: '/study-map'
      path: '/study-map'
      fullPath: '/study-map'
      preLoaderRoute: typeof StudyMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-quiz': {
      id: '/district-quiz'
      path: '/district-quiz'
      fullPath: '/district-quiz'
      preLoaderRoute: typeof DistrictQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictQuizRoute: DistrictQuizRoute,
  StudyMapRoute: StudyMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
